### PR TITLE
upgrade to api version 40

### PR DESCRIPTION
**Pull request by dmgerow**
Updates default api to 40
Adds wsdls for api 40

### CODE REVIEW

**Comment by dcarroll** [comment]
Bump this PR please.

**Comment by john-brock** [comment]
I merged this PR, it will build via our Heroku pipeline CI flow, and then I will need to get Ryan or someone with perms to promote to Prod.

**Comment by ryanbrainard** [comment]
This has been promoted to production. Sorry for the delay here. I was on a long-term leave.

**Comment by dcarroll** [comment]
No worries Ryan!  Thanks a ton!

**Pull request merged**
