### PR TITLE
37.0.0 - SForce API 37 + generic streaming + durable streaming options

### PR DESCRIPTION
**Pull request by john-brock**
1. Add new v37 wsdls
2. Port generic streaming and durable streaming options from internal WB to public WB

### CODE REVIEW

**Comment by john-brock** [comment]
Going to get a few people to quickly look at : https://forceworkbench-staging-pr-683.herokuapp.com/.

**Comment by john-brock** [comment]
@ryanbrainard I have verified the changes on the staging app - could you take a look and merge?

**Comment by john-brock** [comment]
Fixes https://github.com/ryanbrainard/forceworkbench/issues/613 since generic streaming is enabled.

**Comment by ryanbrainard** [comment]
Thanks! Sorry for the delay.

**Comment by ryanbrainard** [comment]
@john-brock Just noticed that this doesn't make any changes to https://github.com/ryanbrainard/forceworkbench/blob/master/workbench/cometdProxy.php, but does introduce https://github.com/ryanbrainard/forceworkbench/blob/master/workbench/util/CometdProxy.php. Was that on purpose? Shouldn't one require the other or something?

**Pull request merged**
